services:
  postgres:
    container_name: postgres
    image: postgres:12.4
    volumes:
      - ./infra/data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: UltimateDevPassword
      POSTGRES_DB: dbadmin
      PGTZ: Europe/Paris

  nats_server:
    image: nats:2.10.7-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./infra/nats-server.conf:/nats-server.conf:ro
      - ./infra/nats-cluster.conf:/nats-cluster.conf:ro
      - ./infra/nats:/nats/storage
    command: ["-n", "nats_server", "--config", "/nats-cluster.conf", "-V"]
    # command: ["-n", "nats_server", "--config", "/nats-server.conf", "-V"]
    restart: always

  nats_server_replica:
    image: nats:2.10.7-alpine
    ports:
      - "4223:4222"
      - "8223:8222"
    volumes:
      - ./infra/nats-cluster.conf:/nats-cluster.conf:ro
      - ./infra/nats:/nats/storage
    command: ["-n", "nats_server_replica", "--config", "/nats-cluster.conf", "-V"]
    restart: always

  nestjs_worker:
    image: node:18.19.0-alpine
    expose:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      WRITE_NATS_URL: nats://nats_server:4222
      READ_NATS_URL: nats://nats_server_replica:4222
    command: ["yarn", "start:dev", "--preserveWatchOutput"]
    deploy:
      replicas: 2
    depends_on:
      - postgres
      - nats_server
    restart: always
